In [1]:
import numpy as np

In [98]:
stocks = 8
years = 30
yearly_periods = 12

trigger = 0.25
commission = 5.50

changes = np.random.normal(size=(stocks, years*yearly_periods))
starts = np.random.poisson(lam=30, size=(stocks, 1))

histories = np.round(np.concatenate((starts, changes), axis=1).cumsum(axis=1), decimals=2)

money_row = np.ones(shape=(1, years*yearly_periods+1))
histories = np.concatenate((money_row, histories), axis=0)

In [99]:
# check if histories don't go non-positive
(histories <= 0).any()

False

value: 99956.0
value: 101258.1
value: 99107.9
value: 99974.1
value: 101214.1
value: 99975.4
value: 98784.8
value: 99816.29999999999
value: 100889.3
value: 100121.3
value: 100093.1
value: 99643.5
value: 100506.9
value: 100610.9
value: 101778.6
value: 99830.3
value: 99298.20000000001
value: 99084.0
value: 99843.5
value: 100014.79999999999
value: 99222.29999999999
value: 98598.9
value: 97713.8
value: 97171.4
value: 97930.20000000001
value: 97989.4
value: 98024.20000000001
value: 99518.8
value: 99329.3
value: 99098.29999999999
value: 101450.5
value: 102344.8
value: 102676.7
value: 102832.19999999998
value: 104040.7
value: 102143.9
value: 100224.3
value: 102188.6
value: 101046.70000000001
value: 101807.6
value: 102223.29999999999
value: 101280.0
value: 101995.3
value: 102615.3
value: 103318.0
value: 102866.9
value: 100471.7
value: 99834.40000000001
value: 100314.5
value: 101471.1
value: 102267.09999999999
value: 101797.09999999999
value: 102291.6
value: 101358.9
value: 101367.4
value: 99623

In [116]:
values, mean_value, percen_diffs, rebalance_purchases, ownership

(array([12876.7, 10890.6, 10271.1, 11056. , 10588.8,  6824.4, 10045. ,
        10695. ,  9455. ]),
 10300.288888888887,
 array([ 0.25012999,  0.05731015, -0.00283379,  0.07336795,  0.02801   ,
        -0.33745548, -0.02478463,  0.03832039, -0.08206458]),
 array([  -0.,   -0.,    0.,   -0.,   -0., 2470.,    0.,   -0.,    0.]),
 array([9388.5,  420. ,  210. ,  400. ,  320. , 7310. ,  700. ,  250. ,
         250. ]))

In [118]:
final

87198.49999999999

In [85]:
bank

10778.0

In [110]:
ownership -np.array([spent] + [0]*stocks) + rebalance_purchases

array([11056.,   380.,   350.,   290.,   360.,   400.,   430.,   280.,
         400.])

In [3]:
stocks = 8
years = 30
yearly_periods = 12
commission = 5.5
final_values = []

for trigger_ in range(1, 101):
    trigger = trigger_/100
    for _ in range(1000):
        first = True
        while first or (histories <= 0).any():
            changes = np.random.normal(scale=1, size=(stocks, years*yearly_periods))
            starts = np.random.poisson(lam=30, size=(stocks, 1))

            histories = np.round(np.concatenate((starts, changes), axis=1).cumsum(axis=1), decimals=2)

            money_row = np.ones(shape=(1, years*yearly_periods+1))
            histories = np.concatenate((money_row, histories), axis=0)
            first = False
        bank = 100000
        ownership = np.array([bank] + [0]*stocks)

        for step in range(years*yearly_periods):
            values = np.multiply(ownership, histories[:,step])
            mean_value = np.mean(values)
            diffs = (values - mean_value)
            percen_diffs = diffs/mean_value
            purchase_spots = np.concatenate((np.zeros(1), np.abs(percen_diffs[1:]) >= trigger))

            rebalance_purchases = np.multiply(-np.round(np.divide(diffs, histories[:,step]), decimals=-1),
                                              purchase_spots)
            spent = np.dot(rebalance_purchases, histories[:,step]) + commission * np.sum(purchase_spots)

            assert bank >= 0
            ownership = ownership - np.array([spent] + [0]*stocks) + rebalance_purchases
        final_values.append(np.dot(ownership, histories[:, -1]))
    print("Trigger:", trigger, 
          "Avg value:", np.round(np.mean(final_values)))

Trigger: 0.01 Avg value: 139599.0
Trigger: 0.02 Avg value: 145525.0
Trigger: 0.03 Avg value: 142597.0
Trigger: 0.04 Avg value: 142930.0
Trigger: 0.05 Avg value: 142649.0
Trigger: 0.06 Avg value: 141882.0
Trigger: 0.07 Avg value: 141800.0
Trigger: 0.08 Avg value: 142212.0
Trigger: 0.09 Avg value: 142700.0
Trigger: 0.1 Avg value: 142446.0
Trigger: 0.11 Avg value: 142602.0
Trigger: 0.12 Avg value: 142365.0
Trigger: 0.13 Avg value: 142719.0
Trigger: 0.14 Avg value: 142450.0
Trigger: 0.15 Avg value: 142463.0
Trigger: 0.16 Avg value: 143045.0
Trigger: 0.17 Avg value: 142984.0
Trigger: 0.18 Avg value: 143319.0
Trigger: 0.19 Avg value: 143242.0
Trigger: 0.2 Avg value: 143331.0
Trigger: 0.21 Avg value: 143685.0
Trigger: 0.22 Avg value: 143655.0
Trigger: 0.23 Avg value: 144057.0
Trigger: 0.24 Avg value: 144059.0
Trigger: 0.25 Avg value: 144019.0
Trigger: 0.26 Avg value: 143982.0
Trigger: 0.27 Avg value: 144070.0
Trigger: 0.28 Avg value: 144171.0
Trigger: 0.29 Avg value: 144351.0
Trigger: 0.3 Avg